name: Deploy API Proxy to EVAL

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-to-eval:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Step 3: Set up Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Step 4: Update and install beta components
      - name: Update and install beta components
        run: |
          gcloud components update --quiet
          gcloud components install beta --quiet
          gcloud --version

      # Step 5: Import proxy (upload only)
      - name: Import API Proxy Revision
        id: import_proxy
        run: |
          echo "Zipping Apigee proxy source..."
          zip -r hello-world.zip apiproxy

          echo "Importing proxy bundle to Apigee X..."
          REVISION=$(gcloud beta apigee apis import "hello-world" \
            --project="${{ secrets.GCP_PROJECT_ID }}" \
            --source="hello-world.zip" \
            --format="value(revision)")

          echo "Imported revision: $REVISION"
          echo "imported_revision=$REVISION" >> $GITHUB_OUTPUT

      # Step 6: Deploy imported revision
      - name: Deploy API Proxy Revision to EVAL
        run: |
          echo "Deploying revision ${{ steps.import_proxy.outputs.imported_revision }} to eval..."
          gcloud beta apigee deployments create \
            --api="hello-world" \
            --project="${{ secrets.GCP_PROJECT_ID }}" \
            --environment="eval" \
            --revision="${{ steps.import_proxy.outputs.imported_revision }}" \
            --format="json"

      # Step 7: Completion message
      - name: Complete job
        run: echo "✅ Successfully imported and deployed hello-world proxy to Apigee X eval environment!"
